name: Mobile Security Scan (MobSF Docker)

on:
  workflow_call:

jobs:
  mobsfscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MobSFScan
        run: |
          pip install --upgrade mobsfscan

      - name: Run MobSFScan
        run: |
          mkdir -p reports
          mobsfscan dvba.apk --json --output reports/results_mobile.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: mobsf-report
          path: reports/
